---
#author:  Abhijeet Janwalkar
#date:    07-09-2022
#version:   0.1
#description: Playbook to PowerOn a  VM 
#Changelog:
# 07-09-2022 - Initial code to Playbook to PowerOn a  VM 

- name: Poweron a  VM by running role poweronVcenterVm
  hosts: localhost
  gather_facts: false
  vars:
    vmName: "{{ morpheus['customOptions']['VMName'] }}"
    vCenter_user: "{{ lookup('cypher','secret=password/password/atvies992qwsrv_user_name') }}"
    vCenter_user_pass: "{{ lookup('cypher','secret=password/password/atvies992qwsrv_user_pass') }}"
    vCenter:
      server: "atvies992qwsrv.admingate.local"
      dataCenter: "DCN-DCS"

  tasks:
  - name: "Running Role: poweronVcenterVm to PowerOn '{{ vmName }}'"
    include_role:
      name: poweronVcenterVm
