---
#author:  Abhijeet Janwalkar
#date:    07-09-2022
#version:   0.1
#description: Playbook to reboot a  VM 
#Changelog:
# 07-09-2022 - Initial code to Playbook to reboot a  VM 

- name: Reboot a  VM by running role rebootVcenterVm
  hosts: localhost
  gather_facts: false

  vars_files:
   # - "{{ input_file }}"
    - /home/ansible/code/vmManagement/vars.yml
  
  vars_prompt:
    - name: "vCenter_user"
      prompt: "Enter  username in the id@domain.name format to Reboot VM in vCenter"
      private: no
    - name: "vCenter_user_pass"
      prompt: "Enter the password for the user. Please note that the password you enter will not be displayed on the screen.\r\nPassword"
      private: yes
    #- name: "input_file"
      #prompt: 'Enter location of input file created from the excel for deploying a VM. example "\home\ansible\vmname.yml"'
      #private: no
    - name: "vmName"
      prompt: 'Enter name of VM to reboot'
      private: no

  tasks:
  - name: "Running Role: rebootVcenterVm to reboot '{{ vmName }}'"
    include_role:
      name: rebootVcenterVm